### ISSUE TITLE
VDU word?

### ISSUE THREAD

**Issue by pawaller** [lennart-benschop/agon-forth#1]
Please would it be possible to have VDU word so we can play with sprites?

Or is this a trivial thing to create my own?

In BBC basic they are using VDU 23, extension 27 to do this.

Many thanks for porting Forth to this platform.
Phil

**Comment by pawaller** [comment]
Hi Lennart,
After reading the VDP documentation it does indeed seem trivial to create the Forth words for VDU commands.
Is there any why to access the *fx 19 OSBYTE command ?

Sorry for the questions, I am new to Agon & the FORTH language

**Comment by lennart-benschop** [comment]
Hi Phil,

The *FX command is interpreted inside BBC Basic. In Basic 1.02 the only 
supported command is *FX 19, the one to wait for the vertical 
synchronization pulse.

You could do this in FORTH like this.

: FX19

   SYSVARS XC@ BEGIN SYSVARS XC@ OVER <> UNTIL DROP ;


MOS 1.03/Basic 1.04 will add several more *FX commands, but they can all 
be implemented using VDU sequences.


--

Lennart

**Comment by pawaller** [comment]
Hi Lennart,
Many thanks I will check it out :-)

I was trying to run your grpdemo.4th which requires graphics.4th but it seems to lose all the words created by graphics.4th.

Am I doing something wrong?

The only way I could proceed was to load graphics.4th and then save that m/c state, then reload and load grpdemo.4th

regards
Phil
