### ISSUE TITLE
ROLL not working correctly in 24 bit version

### ISSUE THREAD

**Issue by pawaller** [lennart-benschop/agon-forth#15]
3 2 1 .S 
3 2 1
2 ROLL .S
2 2 3

or 
5 4 3 2 1 .s
5 4 3 2 1
4 roll .s
4 3 3 2 5

**Comment by lennart-benschop** [comment]
Looks like I have a fix, will push soon.

**Comment by lennart-benschop** [comment]
Was still not working, like 100000 200000 300000 4000000 3 ROLL would mess up. Now another fix to make this work.
