### ISSUE TITLE
TURNKEY word

### ISSUE THREAD

**Issue by pawaller** [lennart-benschop/agon-forth#2]
Hi Lennart,
Sorry it's me again.
Is there a way to implement TURNKEY as in "my-app is turnkey" which runs my-app at startup?

I am using this in Flashforth on Arduino NANO.

Many thanks

**Comment by lennart-benschop** [comment]
Hi Phil,


There is no turnkey facility in Forth at the moment. It may be added in 
later versions. You can run forth with a file name on the command line 
and auto-run a program that way.

--

Lennart

**Comment by pawaller** [comment]
Thanks Lennart
