### ISSUE TITLE
Dictionary full

### ISSUE THREAD

**Issue by pawaller** [lennart-benschop/agon-forth#6]
Hi Lennart,
Sorry for so many questions.

When I compile sokoban.fs ( included in gforth... https://github.com/forthy42/gforth/blob/master/sokoban.fs) I get a "dictionary full" message.
The game does run but when exiting I get the same error message.
I have looked through the code but cannot see anything obvious.
Should I be adding/deleting something to stop this message?

Many thanks
Phil

**Comment by lennart-benschop** [comment]
WHat is your HERE value after compiling sokoban?

here .


I should do an unsigned compare, so I expect you can just fill up until 
nearly 64k. Maze data takes a lot of space, but I'm not sure how much 
exactly.


--

Lennart

**Comment by pawaller** [comment]
I think you are correct, there are 85 mazes.
I pruned this down to 65 and I no longer get the full message. I just assumed there would be a ton a free space.
I don't think the data is very well optimised.
before compiling here . = 16636
after compiling here . = -10146

regards
Phil
